import json
import os
from types import SimpleNamespace

import numpy as np
import torch

from .base import BaseDataset


class SyntheticGrok(BaseDataset):
    """Realizable synthetic regression task for the grokking probe.

    Targets are generated by a frozen MLP teacher of the *same* architecture
    (hidden_dim/n_layers) the student model will use, so the task is exactly
    realizable at noise_std=0 (cs/02381's precondition). Train/test windows
    are drawn i.i.d. from the same generator (no chronological split), so any
    train/test gap is purely a memorize-vs-generalize effect, not covariate
    shift. Subclasses only override `noise_std`.
    """

    noise_std = 0.0
    channels = 7
    n_train = 1374
    n_test = 345
    teacher_seed = 0
    x_seed = 1

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.save_path = os.path.join("datasets", "SyntheticGrok", type(self).__name__)
        self.column_date = None
        self.column_target = [f"c{i}" for i in range(self.channels)]
        self.column_train = [f"c{i}" for i in range(self.channels)]
        self.granularity = 1
        self.granularity_unit = "hour"

    def _make_teacher(self):
        from models.MLP import MLP

        teacher_configs = SimpleNamespace(
            input_len=self.seq_len,
            output_len=self.pred_len,
            hidden_dim=getattr(self.configs, "hidden_dim", None) or 128,
            n_layers=getattr(self.configs, "n_layers", None) or 2,
            dropout=0.0,
        )
        torch.manual_seed(self.teacher_seed)
        teacher = MLP(teacher_configs)
        teacher.eval()
        for p in teacher.parameters():
            p.requires_grad_(False)
        return teacher

    def _make_split(self, teacher, n, rng):
        x = rng.standard_normal((n, self.seq_len, self.channels)).astype(np.float32)
        with torch.no_grad():
            y = teacher(torch.from_numpy(x)).numpy()
        y_mean = y.mean(axis=(0, 1), keepdims=True)
        y_std = y.std(axis=(0, 1), keepdims=True) + 1e-8
        y = (y - y_mean) / y_std
        if self.noise_std > 0:
            y = y + rng.normal(0, self.noise_std, size=y.shape).astype(np.float32)
        y = y.astype(np.float32)
        x_mark = np.zeros((n, self.seq_len, 4), dtype=np.float32)
        y_mark = np.zeros((n, self.pred_len, 4), dtype=np.float32)
        return x, y, x_mark, y_mark

    @staticmethod
    def _channel_stats(arr, columns):
        flat = arr.reshape(-1, arr.shape[-1])
        stats = {}
        for i, col in enumerate(columns):
            stats[col] = {
                "mean": float(flat[:, i].mean()),
                "std": float(flat[:, i].std()) or 1.0,
            }
        return stats

    def execute(self):
        name = f"seq_{self.seq_len}-offset_{self.offset_len}-pred_{self.pred_len}"
        self.path_save = os.path.join(self.save_path, name)
        self.path_info = os.path.join(self.path_save, "info.json")
        self.path_train = os.path.join(self.path_save, "train")
        self.path_test = os.path.join(self.path_save, "test")
        for path in [self.path_save, self.path_train, self.path_test]:
            os.makedirs(path, exist_ok=True)

        if os.path.exists(self.path_info):
            with open(self.path_info, "r", encoding="utf-8") as f:
                self.info = json.load(f)
            return

        teacher = self._make_teacher()
        train_rng = np.random.default_rng(self.x_seed)
        test_rng = np.random.default_rng(self.x_seed + 1)

        train_x, train_y, train_x_mark, train_y_mark = self._make_split(
            teacher, self.n_train, train_rng
        )
        test_x, test_y, test_x_mark, test_y_mark = self._make_split(
            teacher, self.n_test, test_rng
        )

        train_path = os.path.join(self.path_train, "0.npz")
        test_path = os.path.join(self.path_test, "0.npz")
        np.savez_compressed(
            train_path, x=train_x, y=train_y, x_mark=train_x_mark, y_mark=train_y_mark
        )
        np.savez_compressed(
            test_path, x=test_x, y=test_y, x_mark=test_x_mark, y_mark=test_y_mark
        )

        client_info = {
            "client": 0,
            "paths": {"train": train_path, "test": test_path},
            "stats": {
                "train": self._channel_stats(train_x, self.column_train),
                "test": self._channel_stats(test_x, self.column_train),
            },
            "samples": {"train": train_x.shape[0], "test": test_x.shape[0]},
            "input_channels": self.channels,
            "output_channels": self.channels,
            "seq_len": self.seq_len,
            "pred_len": self.pred_len,
            "offset_len": self.offset_len,
            "granularity_unit": self.granularity_unit,
            "noise_std": self.noise_std,
            "teacher_seed": self.teacher_seed,
        }
        self.info = [client_info]
        with open(self.path_info, "w", encoding="utf-8") as f:
            json.dump(self.info, f, indent=4)


class SyntheticGrokNoise01(SyntheticGrok):
    noise_std = 0.1


class SyntheticGrokNoise03(SyntheticGrok):
    noise_std = 0.3


class SyntheticGrokNoise10(SyntheticGrok):
    noise_std = 1.0
